// DEVELOPMENT TEST
### Get all contacts
GET http://localhost:3000/users

### Get contact by ID
GET http://localhost:3000/users/

### Create new User
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Renato",
    "lastName": "Williams",
    "email": "test4@test.com",
    "favoriteColor": "red",
    "birthday": "09/19/1999"
}

### Update User
PUT http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Elias",
    "lastName": "Williams",
    "email": "test4@test.com",
    "favoriteColor": "red",
    "birthday": "09/19/1999"
}

### Delete User
DELETE http://localhost:3000/users/ HTTP/1.1



// PRODUCTION TEST
### Get all contacts
GET https://webservices-project1.onrender.com/users

### Get contact by ID
GET https://webservices-project1.onrender.com/users/

### Create new User
POST https://webservices-project1.onrender.com/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Renato",
    "lastName": "Williams",
    "email": "test4@test.com",
    "favoriteColor": "red",
    "birthday": "09/19/1999"
}

### Update User
PUT https://webservices-project1.onrender.com/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Elias",
    "lastName": "Williams",
    "email": "test4@test.com",
    "favoriteColor": "red",
    "birthday": "09/19/1999"
}

### Delete User
DELETE https://webservices-project1.onrender.com/users/ HTTP/1.1